In [2]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../data/superstore.db")

query = """
SELECT *
FROM superstore
LIMIT 5;
"""

result = pd.read_sql(query, engine)

result

,Order_ID,Invoice_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,Category,Sub_Category,Product_Name,Quantity,Discount,Sales,Profit
0,ORD-10000,INV-50000,2024-04-12,2024-04-13,Second Class,CUST-1075,Customer 0227,Home Office,South,Virginia,Furniture,Chairs,Desk Lamp,6,0.15,1376.680,195.36
1,ORD-10001,INV-50001,2025-03-11,2025-03-15,Standard Class,CUST-1236,Customer 0042,Consumer,East,New Jersey,Technology,Copiers,Monitor,3,0.00,789.880,153.36
2,ORD-10002,INV-50002,2024-09-27,2024-09-30,First Class,CUST-1197,Customer 0134,Home Office,West,Arizona,Office Supplies,Envelopes,Labels,6,0.05,332.730,59.73
3,ORD-10003,INV-50003,2024-04-16,2024-04-20,Second Class,CUST-1009,Customer 0005,Home Office,West,Colorado,Office Supplies,Paper,Labels,1,0.00,107.800,14.52
4,ORD-10004,INV-50004,2024-03-12,2024-03-15,First Class,CUST-1291,Customer 0026,Home Office,East,New York,Technology,Accessories,Printer,5,0.00,3074.035,366.03

In [3]:
query = """
SELECT Customer_Name, Product_Name, Sales, Profit
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

   Customer_Name Product_Name     Sales  Profit
0  Customer 0227    Desk Lamp  1376.680  195.36
1  Customer 0042      Monitor   789.880  153.36
2  Customer 0134       Labels   332.730   59.73
3  Customer 0005       Labels   107.800   14.52
4  Customer 0026      Printer  3074.035  366.03
5  Customer 0060  Binder Pack   322.280   24.37
6  Customer 0046      Monitor  3074.035  366.03
7  Customer 0063       Laptop   742.230  168.50
8  Customer 0177   Smartphone   994.670  153.88
9  Customer 0222  Binder Pack   585.940   95.34

In [4]:
query = """
SELECT Customer_Name, Product_Name, Sales, Profit
FROM superstore
WHERE Sales > 1000
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

   Customer_Name     Product_Name     Sales  Profit
0  Customer 0227        Desk Lamp  1376.680  195.36
1  Customer 0026          Printer  3074.035  366.03
2  Customer 0046          Monitor  3074.035  366.03
3  Customer 0065          Monitor  2682.640  249.77
4  Customer 0182  Wooden Bookcase  1568.610   92.67
5  Customer 0114        Desk Lamp  1241.210   74.18
6  Customer 0249           Laptop  1555.960  366.03
7  Customer 0040  Ergonomic Chair  1578.480  -56.04
8  Customer 0012           Laptop  3074.035  366.03
9  Customer 0222           Laptop  3074.035  366.03

In [5]:
query = """
SELECT Product_Name, Sales
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

     Product_Name     Sales
0         Printer  3074.035
1         Monitor  3074.035
2          Laptop  3074.035
3          Laptop  3074.035
4  Wireless Mouse  3074.035
5         Monitor  3074.035
6         Monitor  3074.035
7         Printer  3074.035
8      Smartphone  3074.035
9         Printer  3074.035

In [7]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)

result

          Category  Total_Sales
0       Technology   468945.015
1        Furniture   328805.085
2  Office Supplies   114124.620

In [8]:
query = """
CREATE TABLE IF NOT EXISTS customers AS
SELECT DISTINCT Customer_ID, Customer_Name
FROM superstore;
"""

with engine.begin() as connection:
    connection.exec_driver_sql(query)

print("Customer table created")

Customer table created

In [9]:
query = """
SELECT s.Order_ID,
       s.Customer_ID,
       c.Customer_Name,
       s.Sales
FROM superstore s
JOIN customers c
ON s.Customer_ID = c.Customer_ID
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

    Order_ID Customer_ID  Customer_Name    Sales
0  ORD-10000   CUST-1075  Customer 0019  1376.68
1  ORD-10000   CUST-1075  Customer 0121  1376.68
2  ORD-10000   CUST-1075  Customer 0177  1376.68
3  ORD-10000   CUST-1075  Customer 0183  1376.68
4  ORD-10000   CUST-1075  Customer 0227  1376.68
5  ORD-10000   CUST-1075  Customer 0239  1376.68
6  ORD-10001   CUST-1236  Customer 0042   789.88
7  ORD-10001   CUST-1236  Customer 0210   789.88
8  ORD-10001   CUST-1236  Customer 0222   789.88
9  ORD-10001   CUST-1236  Customer 0246   789.88

In [10]:
query = """
SELECT Product_Name, Sales
FROM superstore
WHERE Sales > (
    SELECT AVG(Sales)
    FROM superstore
)
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

      Product_Name     Sales
0        Desk Lamp  1376.680
1          Printer  3074.035
2          Monitor  3074.035
3       Smartphone   994.670
4          Monitor  2682.640
5  Wooden Bookcase  1568.610
6        Desk Lamp  1241.210
7           Laptop  1555.960
8  Ergonomic Chair  1578.480
9           Laptop  3074.035

In [11]:
query = """
WITH category_sales AS (
    SELECT Category,
           SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Category
)
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Sales
0       Technology   468945.015
1        Furniture   328805.085
2  Office Supplies   114124.620

In [12]:
query = """
SELECT Product_Name,
       Sales,
       ROW_NUMBER() OVER (ORDER BY Sales DESC) AS Row_Number
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

     Product_Name     Sales  Row_Number
0         Printer  3074.035           1
1         Monitor  3074.035           2
2          Laptop  3074.035           3
3          Laptop  3074.035           4
4  Wireless Mouse  3074.035           5
5         Monitor  3074.035           6
6         Monitor  3074.035           7
7         Printer  3074.035           8
8      Smartphone  3074.035           9
9         Printer  3074.035          10

In [13]:
query = """
SELECT Product_Name,
       Sales,
       RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

     Product_Name     Sales  Sales_Rank
0         Printer  3074.035           1
1         Monitor  3074.035           1
2          Laptop  3074.035           1
3          Laptop  3074.035           1
4  Wireless Mouse  3074.035           1
5         Monitor  3074.035           1
6         Monitor  3074.035           1
7         Printer  3074.035           1
8      Smartphone  3074.035           1
9         Printer  3074.035           1

In [14]:
query = """
SELECT Order_Date,
       Sales,
       LAG(Sales) OVER (ORDER BY Order_Date) AS Previous_Sales
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

   Order_Date     Sales  Previous_Sales
0  2024-01-01  2939.520             NaN
1  2024-01-01  1778.660        2939.520
2  2024-01-01    56.600        1778.660
3  2024-01-02   100.140          56.600
4  2024-01-02  3074.035         100.140
5  2024-01-02   381.050        3074.035
6  2024-01-03  3074.035         381.050
7  2024-01-04  2062.040        3074.035
8  2024-01-05   396.730        2062.040
9  2024-01-05   197.700         396.730

In [15]:
query = """
SELECT Order_Date,
       Sales,
       LEAD(Sales) OVER (ORDER BY Order_Date) AS Next_Sales
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

   Order_Date     Sales  Next_Sales
0  2024-01-01  2939.520    1778.660
1  2024-01-01  1778.660      56.600
2  2024-01-01    56.600     100.140
3  2024-01-02   100.140    3074.035
4  2024-01-02  3074.035     381.050
5  2024-01-02   381.050    3074.035
6  2024-01-03  3074.035    2062.040
7  2024-01-04  2062.040     396.730
8  2024-01-05   396.730     197.700
9  2024-01-05   197.700      97.160

In [16]:
query = """
CREATE VIEW IF NOT EXISTS category_sales AS
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category;
"""

with engine.begin() as connection:
    connection.exec_driver_sql(query)

print("View created")

View created

In [17]:
query = """
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Sales
0       Technology   468945.015
1        Furniture   328805.085
2  Office Supplies   114124.620

Q1. What are the top 5 products by sales?

In [18]:
query = """
SELECT Product_Name,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Product_Name
ORDER BY Total_Sales DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

      Product_Name  Total_Sales
0          Monitor   129492.370
1   Wireless Mouse   101125.645
2           Laptop    97637.460
3  Wooden Bookcase    87961.915
4     Office Table    81849.455

Q2. What is the monthly sales trend?

In [19]:
query = """
SELECT strftime('%Y-%m', Order_Date) AS Month,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

result = pd.read_sql(query, engine)
result

      Month  Total_Sales
0   2024-01    52241.800
1   2024-02    39064.620
2   2024-03    27776.810
3   2024-04    44876.420
4   2024-05    35819.555
5   2024-06    43557.650
6   2024-07    27807.555
7   2024-08    49434.930
8   2024-09    36548.150
9   2024-10    28090.380
10  2024-11    27989.560
11  2024-12    33215.650
12  2025-01    59033.280
13  2025-02    36604.920
14  2025-03    39088.835
15  2025-04    42935.750
16  2025-05    40659.280
17  2025-06    27549.890
18  2025-07    43238.510
19  2025-08    16035.950
20  2025-09    21399.720
21  2025-10    58153.540
22  2025-11    54232.925
23  2025-12    26519.040

Q3. What are the top 5 customers by spending?

query = """
SELECT Customer_Name,
       SUM(Sales) AS Total_Spending
FROM superstore
GROUP BY Customer_Name
ORDER BY Total_Spending DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

In [21]:
query = """
SELECT Customer_Name,
       SUM(Sales) AS Total_Spending
FROM superstore
GROUP BY Customer_Name
ORDER BY Total_Spending DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

   Customer_Name  Total_Spending
0  Customer 0114       32073.740
1  Customer 0229       13813.485
2  Customer 0065       11564.720
3  Customer 0210       11081.495
4  Customer 0249       10600.740

Q4. What are total sales by category?

In [22]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Sales
0       Technology   468945.015
1        Furniture   328805.085
2  Office Supplies   114124.620

Q5. What are total sales by region?

In [23]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

    Region  Total_Sales
0  Central   235703.540
1     West   234372.325
2     East   231111.460
3    South   210687.395

Q6. What is the total profit by category?

In [24]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Profit
0       Technology      61386.41
1        Furniture      29267.21
2  Office Supplies      17713.07

Q7. How many orders are there?

In [25]:
query = """
SELECT COUNT(DISTINCT Order_ID) AS Total_Orders
FROM superstore;
"""

result = pd.read_sql(query, engine)
result

   Total_Orders
0          1000

Q8. What is the average sales amount?

query = """
SELECT AVG(Sales) AS Average_Sales
FROM superstore;
"""

result = pd.read_sql(query, engine)
result

In [26]:
query = """
SELECT AVG(Sales) AS Average_Sales
FROM superstore;
"""

result = pd.read_sql(query, engine)
result

   Average_Sales
0      911.87472

Q9. Which category has the highest profit?

In [27]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC
LIMIT 1;
"""

result = pd.read_sql(query, engine)
result

     Category  Total_Profit
0  Technology      61386.41

Q10. Which orders made a loss?

In [ ]:
query = """
SELECT Order_ID,
       Product_Name,
       Sales,
       Profit
FROM superstore
WHERE Profit < 0
ORDER BY Profit ASC
LIMIT 20;
"""

result = pd.read_sql(query, engine)
result

     Order_ID     Product_Name    Sales  Profit
0   ORD-10017  Ergonomic Chair  1578.48  -56.04
1   ORD-10041     Office Table   835.73  -37.71
2   ORD-10449  Ergonomic Chair  2553.85  -34.61
3   ORD-10025     Office Table  1476.62  -33.64
4   ORD-10958  Wooden Bookcase  1189.82  -33.33
5   ORD-10434     Office Table  2004.83  -26.05
6   ORD-10270  Ergonomic Chair  2413.47  -22.85
7   ORD-10175        Desk Lamp  1218.21  -16.55
8   ORD-10323  Wooden Bookcase  1274.85  -13.79
9   ORD-10681  Wooden Bookcase   242.62  -12.96
10  ORD-10349      Binder Pack   576.63  -11.98
11  ORD-10739        Desk Lamp  1042.34   -9.70
12  ORD-10571  Ergonomic Chair   303.81   -8.19
13  ORD-10235  Ergonomic Chair   887.54   -5.39
14  ORD-10386     Office Table   287.03   -4.31
15  ORD-10321           Labels   128.03   -2.93
16  ORD-10504  Wooden Bookcase  1462.32   -1.67
17  ORD-10536  Wooden Bookcase   330.60   -1.53
18  ORD-10973      Binder Pack    89.31   -1.34
19  ORD-10443  Ergonomic Chair   141.39   -1.29